config/routes.rb
Rails.application.routes.draw do
  get 'contact', to: 'pages#contact', as: :contact
  get 'about', to: 'pages#about', as: :about
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :articles
  resources :cinemas do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_taggable_on :tags
end

app/models/cinema.rb
class Cinema < ApplicationRecord
  has_many :reviews, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cinema
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
 class ArticlesController < ApplicationController
  def index
    if params[:tag].present?
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.all
    end # GET /restaurants
  end

  def show
    @article = Article.find(params[:id])
    @related_articles = @article.find_related_tags        # GET /restaurants/:id
  end

  def new
    @article = Article.new      # GET /restaurants/new
  end

  def create
    @article = Article.new(article_params)
    @article.save

    redirect_to article_path(@article)
  end

  def edit          # GET /restaurants/:id/edit
    @article = Article.find(params[:id])       # POST /restaurants
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    redirect_to article_path(@article)    # PATCH /restaurants/:id
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to articles_path      # DELETE /restaurants/:id
  end

  private

  def article_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:article).permit(:title, :content, :tag_list)
  end
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController
  def index
    @cinemas = Cinema.all.where.not(latitude: nil, longitude: nil)

    @markers = @cinemas.map do |cinema|
      {
        lat: cinema.latitude,
        lng: cinema.longitude
      }
    end
  end

  def show
    @cinema = Cinema.find(params[:id])
    @reviews = Review.where(cinema_id: @cinema.id)
  end

  def new
    @cinema = Cinema.new
  end

  def create
    @cinema = Cinema.new(cinema_params)
    @cinema.save

    redirect_to cinema_path(@cinema)
  end

  def edit
    @cinema = Cinema.find(params[:id])
  end

  def update
    @cinema = Cinema.find(params[:id])
    @cinema.update(cinema_params)

    redirect_to cinema_path(@cinema)
  end

  def destroy
    @cinema = Cinema.find(params[:id])
    @cinema.destroy

    redirect_to cinemas_path
  end

  private

  def cinema_params
    params.require(:cinema).permit(:name, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # we need @cinema in our `simple_form_for`
    @cinema = Cinema.find(params[:cinema_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `cinema_id` to asssociate review with corresponding cinema
    @review.cinema = Cinema.find(params[:cinema_id])
    @review.save

    redirect_to cinema_path(@review.cinema)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :user_name, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<%= form_for(@article) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/articles/index.html.erb
<% array = [] %>
<% arr = [] %>
<% @articles.each do |article| %>
<% article.tag_list.each do |tage| %>
<% array << tage %>
<% end %>
<% end %>
<% array.uniq.each do |tag| %>
<%= link_to tag, articles_path(tag: tag) %>
<% end %>



<% @articles.each do |article| %>
<h2><%= link_to article.title, article_path(article) %></h2>
<p><%= article.content %>
  <br>
  <br>
  <% article.tag_list.each do |tag| %>
  <%= link_to tag, articles_path(tag: tag) %>
  <% end %>
</p>
<% end %>

<h2><%= link_to 'New', new_article_path(@article) %></h2>
<h2><% if params[:tag].present? %></h2>
<h2><%=link_to 'Go Back', articles_path %></h2>
<% end %>

app/views/articles/new.html.erb
<!-- <%#= form_for(@article) do |f| %>
  <div class="form-group">
    <%#= f.label :title %>
    <%#= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%#= f.label :content %>
    <%#= f.text_field :content, class: 'form-control' %>
  </div>

  <%#= f.submit class: 'btn btn-primary' %>
<#% end %>
 -->

 <%= simple_form_for @article do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <!-- Add tags as a comma separated list -->
  <%= f.input :tag_list, label: "Add tags", hint: "Add your tags, separated by commas" %>
  <!-- Add tags as checkboxes -->
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<p><%= @article.content %></p>

<h3>Related Articles</h3>
<ul>
  <% @related_articles.each do |r| %>
    <li><%= r.title %></li>
  <% end %>
</ul>

<%= link_to "Delete", article_path(@article),
      method: :delete,
      data: { confirm: "Are you sure?" } %>

<h2><%= link_to 'Update', edit_article_path(@article) %></h2>

<h2><%= link_to 'Go back', articles_path %></h2>

app/views/cinemas/edit.html.erb
<%= form_for(@cinema) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/cinemas/index.html.erb
<% @cinemas.each do |cinema| %>
  <h2><%= link_to cinema.name, cinema_path(cinema) %></h2>
  <p><%= cinema.address %></p>
<% end %>


<h2><%= link_to 'New', new_cinema_path(@cinema) %></h2>

<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/cinemas/new.html.erb
<%= form_for(@cinema) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/cinemas/show.html.erb
<h2><%= @cinema.name %></h2>
<p><%= @cinema.address %></p>

<% @reviews.each do |review| %>
<!--   <h2><%= review.rating %></h2> -->
 <% unless review.rating.nil? %>
      <% nb_stars = review.rating.round.to_i %>
      <% nb_stars.times do %>
        <span style="color: #2F2FA2"><i class="fas fa-star"></i></span>
      <% end %>
      <% (5 - nb_stars).times do %>
        <span style="color: #2F2FA2"><i class="far fa-star"></i></span>
      <% end %>
     <% end %>
  <p><%= review.content %></p>
  <p><%= review.user_name %></p>
<% end %>

<%= link_to "Delete", cinema_path(@cinema),
      method: :delete,
      data: { confirm: "Are you sure?" } %>

<h2><%= link_to 'Update', edit_cinema_path(@cinema) %></h2>

<h2><%= link_to 'Review', new_cinema_review_path(@cinema) %></h2>

<h2><%= link_to 'Go back', cinemas_path %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-1">
  <div class="container">
    <div class="title-home">
      <div class="boxed boxed-inner">
        <div class="vertical-title hidden-xs hidden-sm">
          <span>INTRODUCE</span>
        </div>
        <h1>ŌMA</h1>
        <h1>VERTICAL CINEMA</h1>
        <div class="color-bar"></div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [@cinema, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience"%>
  <%= f.input :user_name %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= yield(:navbar_class) %>">

  <%= link_to "/", class: "navbar-brand" do %>
  <%#= image_tag 'logo.png', class: "logo" %>
  <% end %>
 <div class="collapse navbar-collapse mr-5" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <label>
      <span class="menu">
        <span class="hamburger"></span>
      </span>
      <ul>
        <li class="nav-item">
          <%= link_to "What is Ōma ?", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Experience", class: "nav-link" %>
        </li>
        <li class="nav-item mr-3">
          <%= link_to "Contact", class: "nav-link" %>
        </li>
      </ul>
    </label>
  </ul>
</div>
</div>